---
apiVersion: v1
kind: Pod
metadata:
  name: finservpoda
  labels:
     app: tsdata
spec:
  containers:
  - name: gettsdata
    image: jpworkshop.azurecr.io/timeseries
    tty: true

  - name: pushtsdata
    image: jpworkshop.azurecr.io/timeseries
    tty: true
